# Generated by Django 5.2.7 on 2025-11-04 08:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('model_type', models.CharField(choices=[('decision_tree', 'Decision Tree'), ('association_rules', 'Association Rules'), ('other', 'Other')], max_length=32)),
                ('file_path', models.CharField(help_text='Relative path to the serialized model artifact.', max_length=255)),
                ('version', models.CharField(default='1.0.0', max_length=32)),
                ('trained_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
