# Generated by Django 5.2.7 on 2025-11-04 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=16)),
                ('employment_status', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Self-employed', 'Self-employed'), ('Unemployed', 'Unemployed'), ('Student', 'Student'), ('Retired', 'Retired')], max_length=32)),
                ('occupation', models.CharField(max_length=64)),
                ('education', models.CharField(max_length=64)),
                ('household_size', models.PositiveSmallIntegerField()),
                ('has_children', models.BooleanField(default=False)),
                ('monthly_income_sgd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preferred_category_label', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_customers', to='catalog.productcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
