# Generated by Django 5.2.7 on 2025-11-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customerprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='shipping_address_line_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='shipping_address_line_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='shipping_contact_number',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='shipping_full_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='shipping_postal_code',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
